### ISSUE TITLE
Badge Mode won't save/load if set to Still Image or Slideshow

### ISSUE THREAD

**Issue by GhostSonic21** [PhoenixbornTech/DigiBadge_Mini#21]
Flag mode and Color mode works fine for saving. Probably just a flags issue.

**Comment by Andon-A** [comment]
Found at least part of it. Flash is started before the SD card. In the Flash bit, when loading, it checks the number of images on the card. If it's zero, it resets it.

Guess what - Images are only counted after the SD card is started, for obvious reasons.

I'll be flipping these and double-checking for other errors.

**Comment by Andon-A** [comment]
Commit https://github.com/PhoenixbornTech/DigiBadge_Mini/commit/f57dc92b90c6c85ee3cc7d2d009534e7bb0dc764 fixes this issue.
